name: reflectify
description: A futuristic journaling app
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  table_calendar: ^3.2.0
  intl: ^0.20.2
  flutter_riverpod: ^3.0.3
  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  firebase_database: ^12.0.3
  provider: ^6.1.5+1
  riverpod: ^3.0.3
  state_notifier: ^1.0.0
  image_picker: ^1.2.0
  geolocator: ^14.0.2
  fl_chart: ^1.1.1
  glass_kit: ^4.0.2
  uuid: ^4.5.1
  shared_preferences: ^2.3.4
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  flutter_slidable: ^4.0.3
  percent_indicator: ^4.2.3
  http: ^1.2.2
  markdown: ^7.2.2  # Replacing discontinued flutter_markdown

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/grid.jpg
    - assets/bg_mad.jpg

  fonts:
    - family: BebasNeue
      fonts:
        - asset: fonts/BebasNeue-Regular.ttf
        
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf