name: reflectify
description: A futuristic journaling app
publish_to: "none"

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  glass_kit: ^2.0.1
  table_calendar: ^3.0.9  
  intl: ^0.19.0    # For date formatting
  flutter_riverpod: ^3.0.3  
  cupertino_icons: ^1.0.5
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  firebase_database: ^12.0.3
  provider: ^6.1.5
  riverpod: ^3.0.3
  image_picker: ^1.1.1
  geolocator: ^14.0.2
  fl_chart: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
