// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD31--RwgkJvj2aIBWOUNNNfnV-8XeBQ24',
    appId: '1:351109881477:web:8c23c3c668d7af7765d3ec',
    messagingSenderId: '351109881477',
    projectId: 'reflectify-b3958',
    authDomain: 'reflectify-b3958.firebaseapp.com',
    databaseURL: 'https://reflectify-b3958-default-rtdb.firebaseio.com',
    storageBucket: 'reflectify-b3958.firebasestorage.app',
    measurementId: 'G-J8NFFHZT33',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3EIZu8Vj5jPhg3RedgAPIsYnnqKV2Vo0',
    appId: '1:351109881477:android:00e01e951a29b63665d3ec',
    messagingSenderId: '351109881477',
    projectId: 'reflectify-b3958',
    databaseURL: 'https://reflectify-b3958-default-rtdb.firebaseio.com',
    storageBucket: 'reflectify-b3958.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3a0TbG7b1nl6Nd1rxhPlxWqwaRTtnIcs',
    appId: '1:351109881477:ios:e194453876257a8365d3ec',
    messagingSenderId: '351109881477',
    projectId: 'reflectify-b3958',
    databaseURL: 'https://reflectify-b3958-default-rtdb.firebaseio.com',
    storageBucket: 'reflectify-b3958.firebasestorage.app',
    iosBundleId: 'com.example.reflectify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3a0TbG7b1nl6Nd1rxhPlxWqwaRTtnIcs',
    appId: '1:351109881477:ios:e194453876257a8365d3ec',
    messagingSenderId: '351109881477',
    projectId: 'reflectify-b3958',
    databaseURL: 'https://reflectify-b3958-default-rtdb.firebaseio.com',
    storageBucket: 'reflectify-b3958.firebasestorage.app',
    iosBundleId: 'com.example.reflectify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD31--RwgkJvj2aIBWOUNNNfnV-8XeBQ24',
    appId: '1:351109881477:web:0b6553d66dd8320065d3ec',
    messagingSenderId: '351109881477',
    projectId: 'reflectify-b3958',
    authDomain: 'reflectify-b3958.firebaseapp.com',
    databaseURL: 'https://reflectify-b3958-default-rtdb.firebaseio.com',
    storageBucket: 'reflectify-b3958.firebasestorage.app',
    measurementId: 'G-QCZTCKCHM2',
  );
}
